version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5555:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    tty: true
    user: root
    restart: always
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/testdb?sslmode=disable
    links:
      - postgres:postgres
    restart: always
    depends_on:
      - postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pgsql-data:
    driver: local
